version: '3'
services:
  application:
    container_name: flaskapp
    image: rahulunixsa87/flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DB: mydb
    depends_on:
    - mysql

  mysql:
    container_name: mysql-5.7
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql   # Mount sql script into container's /docker-entrypoint-initdb.d directory to get table automatically created ( also called DB seeding )
      - mysql-data:/var/lib/mysql  # Mount the volume for MySQL data storage

volumes:
  mysql-data:
